### PR TITLE
replace usage to set-output

### PR DESCRIPTION
**Pull request by jburel**
Remove the usage of the deprecated approach

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
This change is inline with the approach we have been rolling out across the board e.g. https://github.com/ome/bioformats/pull/3893. 

As the workflow is only executed during the `upload` phase, should we consider tagging e.g. 5.6.5-1 to confirm it is working ?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#2034](https://ci.openmicroscopy.org/job/DOCKER-merge/2034/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/2034/consoleText) for more details.
Possible conflicts:
  - PR #63 jburel 'Labels'
    - .github/workflows/main.yml

--conflicts

**Comment by sbesson** [comment]
Interestingly, as reported by the conflict comment above, https://github.com/ome/omero-server-docker/pull/63 achieves the same goal with a potential added functionality (label metadata). Which approach do you favor @jburel ?

**Comment by jburel** [comment]
I think #63 is better. I completely forgot about that PR

**Comment by jburel** [comment]
merging. I will look at labels post release

**Pull request merged**
