### PR TITLE
Labels

### PR DESCRIPTION
**Pull request by jburel**
* Clean up the action to match changes made in https://github.com/ome/omero-web-docker/pull/63
* Add labels during the build process via gha

### CODE REVIEW

**Review by sbesson — COMMENTED** [review]
Looks good to me although obviously completely untested. Should we evaluate a staging image to ensure the metadata is present?

**Comment by joshmoore** [comment]
@sbesson: that sounds like a great plan. But at the moment, is there really a staging provision? I assume most of the main used tags get bumped.

**Comment by jburel** [comment]
One option could be to push to a personal account

**Comment by joshmoore** [comment]
If you have one setup, J-m, definitely happy to try it out.

**Comment by sbesson** [comment]
> But at the moment, is there really a staging provision? 

No indeed there is nothing automatic to the best of my knowledge at the moment. For the avoidance of doubt, I did not mean to raise the priority of this feature even though I am interesting by the outcome of the test.

Main reason for bringing it up is that we closed https://github.com/ome/omero-server-docker/pull/74 in favor of this PR as per the additional metadata feature. So we might also simply consider re-opening and merging #74 first and then get this reviewed post OMERO 5.6.6 release

**Comment by jburel** [comment]
Putting that on-hold. Several things to do before the break.
I will get back to it after the release

**Pull request closed without merging**
