### PR TITLE
Re-activate dropbox test

### PR DESCRIPTION
**Pull request by joshmoore**

### CODE REVIEW

**Comment by joshmoore** [comment]
```
+echo 'Failed to find image'
```
I assume that https://github.com/ome/omero-dropbox/pull/13 will correction the issue.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by joshmoore** [comment]
I'll try a push to remove git. Likely it was just the use of something intermediary. I'll also try to pin to PG 11. cc: @jburel

**Comment by joshmoore** [comment]
Green again with ome.postgresql 4.0.0. Releasing.

**Pull request merged**
