### PR TITLE
Add label

### PR DESCRIPTION
**Pull request by jburel**
* Upgrade action to avoid deprecation warning
* Use docker/metadata-action

Commits tested via https://hub.docker.com/repository/docker/jburel/omero-server

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Comparing the metadata of the last published Docker image

```
(base) [sbesson@idr2-slot3 ~]$ docker inspect openmicroscopy/omero-server:5.6.6 | grep -A 16 Labels
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "omero-server",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4063/tcp": {},
                "4064/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
--
            "Labels": {
                "maintainer": "ome-devel@lists.openmicroscopy.org.uk",
                "org.label-schema.build-date": "20201113",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS",
                "org.opencontainers.image.created": "unknown",
                "org.opencontainers.image.licenses": "GPL-2.0-only",
                "org.opencontainers.image.revision": "unknown",
                "org.opencontainers.image.source": "https://github.com/openmicroscopy/omero-server-docker",
                "org.opencontainers.image.title": "CentOS Base Image",
                "org.opencontainers.image.vendor": "CentOS"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
```

vs the tag produced from the HEAD of this branch

```
(base) [sbesson@idr2-slot3 ~]$ docker inspect jburel/omero-server:5.6.7-4 | grep -A 16 Labels
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "omero-server",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4063/tcp": {},
                "4064/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
--
            "Labels": {
                "maintainer": "ome-devel@lists.openmicroscopy.org.uk",
                "org.label-schema.build-date": "20201113",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS",
                "org.opencontainers.image.created": "2023-02-21T16:42:10.042Z",
                "org.opencontainers.image.description": "OMERO.server production docker image",
                "org.opencontainers.image.licenses": "BSD-2-Clause",
                "org.opencontainers.image.revision": "c31fd9fb793d984568e60b6ab95ab2479b15ef26",
                "org.opencontainers.image.source": "https://github.com/jburel/omero-server-docker",
                "org.opencontainers.image.title": "omero-server-docker",
                "org.opencontainers.image.url": "https://github.com/jburel/omero-server-docker",
                "org.opencontainers.image.vendor": "CentOS",
                "org.opencontainers.image.version": "5.6.7-4"
            }
```

It looks like the current logic is broken anyways. This commit uses upstream workflows to populate meaningful information about the source of the image. Incidentally, it also removes unnecessary layers in the `Dockerfile`.

I do not see any immediate downside to using this strategy moving forward.

**Comment by joshmoore** [comment]
Only thing I notice is that there is a different license (BSD) under org.opencontainers.image.licenses -- I don't know what semantics are intended there (of the image or the contents of the image)

**Comment by jburel** [comment]
That's interesting since we did not specify the licenses label

**Comment by joshmoore** [comment]
Maybe that's just a change in the plugin to use the local repo since https://github.com/ome/omero-server-docker/blob/master/LICENSE.md is BSD

**Pull request merged**
