### PR TITLE
use ubuntu 20.04 as base instead of CentOS7

### PR DESCRIPTION
**Pull request by glyg**
Following this discussion: https://github.com/ome/omero-web-docker/issues/67 (it's on the web image, sorry) I ported the DockerFile to ubuntu, which is quite painless thanks to ansible being already aware of ubuntu 20.04

questions:
- [ ] how to add sha256 information in the `FROM` line (not sure where that info is)
- [ ] understand why the PATH is changed here and not on the playbooks
- [ ] maybe trim the image a bit more?

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#1974](https://ci.openmicroscopy.org/job/DOCKER-merge/1974/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/1974/consoleText) for more details.
Possible conflicts:
  - PR #2 dpwrussell 'Enable public user'
    - Dockerfile
  - PR #19 joshmoore 'SQL backup/restore (WIP)'
    - Dockerfile
  - PR #63 jburel 'Labels'
    - Dockerfile
  - PR #68 dependabot[bot] 'Bump centos from `dead07b` to `c73f515`'
    - Dockerfile

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#1975](https://ci.openmicroscopy.org/job/DOCKER-merge/1975/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/1975/consoleText) for more details.
Possible conflicts:
  - PR #2 dpwrussell 'Enable public user'
    - Dockerfile
  - PR #19 joshmoore 'SQL backup/restore (WIP)'
    - Dockerfile
  - PR #63 jburel 'Labels'
    - Dockerfile
  - PR #68 dependabot[bot] 'Bump centos from `dead07b` to `c73f515`'
    - Dockerfile

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#1976](https://ci.openmicroscopy.org/job/DOCKER-merge/1976/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/1976/consoleText) for more details.
Possible conflicts:
  - PR #2 dpwrussell 'Enable public user'
    - Dockerfile
  - PR #19 joshmoore 'SQL backup/restore (WIP)'
    - Dockerfile
  - PR #63 jburel 'Labels'
    - Dockerfile
  - PR #68 dependabot[bot] 'Bump centos from `dead07b` to `c73f515`'
    - Dockerfile

--conflicts

**Comment by joshmoore** [comment]
Sorry for the @snoopycrimecop noise, @glyg. I'll close some of the older PRs so we can evaluate this. FWIW, @chris-allan mentioned needed to continue supporting rhel/centos 7 (as well as 9) for some time and that that rocky linux images are another possible option.

**Comment by glyg** [comment]
> @glyg, are you using this in production? 
No we deploy our own image (with added plugins) here:

https://gitlab.in2p3.fr/fbi-data/dockers-projects/omero-server 

regarding the CI discussion, I think we'll be looking into adapting it to gitlab CI — which might provide some biodiversity, if or when the time comes github "enshityfies" :þ

**Comment by glyg** [comment]
I am closing this, as the work to change base images is ongoing at the ansible level on https://github.com/ome/omero-server-docker/issues/79

**Pull request closed without merging**
